### PR TITLE
Fixes #10 - Adds coverage output in terminal

### LINKED ISSUE #10: Output coverage in terminal
Gitlab recommends using simplecov-cobertura in their documentation.  Elsewhere, they have recommended coverage regex parsing for badge creation, but simplecov-cobertura doesn't output what they're looking for.  The HTML formatter does, though

HTML Output:
> Coverage report generated for Unit Tests to /project/path/coverage. 67 / 67 LOC (100.0%) covered.

Cobertura Output:
> Coverage report generated for Unit Tests to /Users/jbowes/temp/pagecheck/coverage/coverage.xml

Investigate adding the coverage to stdout for simplecov-cobertura

### PR DESCRIPTION
**Pull request by pramodshinde**
Is this a legitimate? 

```bash
Coverage report generated for RSpec to /app/coverage/coverage.xml 4605 / 15634 LOC (29.46%) covered.
Coverage report generated for RSpec to /app/coverage. 4605 / 15634 LOC (29.46%) covered
```

### CODE REVIEW

**Comment by jessebs** [comment]
Thank you very much!  A couple of small things.  Could you add a period after the coverage.xml in the output to make it consistent with the output of the default formatter?  And what do you think about testing the stdout?  https://stackoverflow.com/a/22777806/1449987 might be a good reference.

**Comment by pramodshinde** [comment]
@jessebs Sure will address requested suggestions

**Comment by jessebs** [comment]
Thank you, @pramodshinde .  I'm looking forward to merging it in.

**Comment by pramodshinde** [comment]
@jessebs Addressed all the suggestions and amended changes

**Pull request merged**
