### PR TITLE
XML Version

### PR DESCRIPTION
**Pull request by rlester**
- For conistency sake converted all single quotes in coverage.xml to double quotes.
- Added XML version header.

### CODE REVIEW

**Comment by jessebs** [comment]
Thank you very much for the pull request.  It looks like none of the build failures are a direct result of your change.  I will review your change in more detail and will merge in the next few days if I don't find anything concerning.

**Comment by rlester** [comment]
Sounds good, let me know if you need any clarification.

**Comment by rlester** [comment]
@jessebs Any update on the review?

**Comment by jessebs** [comment]
Not yet.  I'll have it done by the end of this weekend.

**Comment by jessebs** [comment]
No issues will the pull request.  All merged in and a new version has been pushed to rubygems - version 1.2.0.

**Comment by rlester** [comment]
@jessebs Thanks you!

**Pull request merged**
