### PR TITLE
Add rexml dependency & enable ruby 3.0 

### PR DESCRIPTION
**Pull request by tonobo**

### CODE REVIEW

**Comment by tonobo** [comment]
According to git bisect, it seems simplecov has changed a bit -> https://github.com/simplecov-ruby/simplecov/commit/ed03db5d65563c5e7be3f15892f77ad045b4351d

**Comment by jessebs** [comment]
Thank you for making this change.  I just installed Ruby 3 and will review the changes over the next week or so.

**Comment by skcc321** [comment]
any updates on that one?

**Comment by jessebs** [comment]
No update - Time got away from me.  I'll prioritize it over the coming week

**Comment by jessebs** [comment]
Thank you for the contribution.  This was done as part of #21, which was merged today.

**Pull request closed without merging**
